### ISSUE TITLE
Mysql INT(10) unsigned column to row.getLong throws exception

### ISSUE THREAD

**Issue by coud** [jasync-sql/jasync-sql#102]
INT(10) unsigned in mysql has limit up to 4b+ and when use with getLong of row, it throws java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long. Java's integer is signed and limit is up to 2b+ so long data type is the appropriate data type for mysql unsigned int. It seems the typesafety uses column datatype and does not consider it being signed or unsigned but the problem is it enforces that type even if you call a different get{Type} method.

**Comment by oshai** [comment]
Can you please provide the stack trace?

**Comment by coud** [comment]
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at com.github.jasync.sql.db.RowData$DefaultImpls.getLong(RowData.kt:48) ~[jasync-common-0.9.23.jar:?]
	at com.github.jasync.sql.db.general.ArrayRowData.getLong(ArrayRowData.kt:5) ~[jasync-common-0.9.23.jar:?]
	at com.richdevt.hthookserver.repository.ProjectRepository.findProjectEnvironment(ProjectRepository.kt:29) ~[classes/:?]
	at com.richdevt.hthookserver.repository.ProjectRepository$findProjectEnvironment$3.invokeSuspend(ProjectRepository.kt) ~[classes/:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32) [kotlin-stdlib-1.3.21.jar:1.3.21-release-158 (1.3.21)]
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152
```

**Comment by oshai** [comment]
I don't think the problem is related to type safety. Since Java doesn't have unsigned types the driver treats it as a signed type. As a workaround, you can get it as a signed int and then wide-convert it like suggested here: https://stackoverflow.com/questions/9578639/best-way-to-convert-a-signed-integer-to-an-unsigned-long
Let me know if that helps.

**Comment by coud** [comment]
I used the getAs<T>() and that respects what type I want for the integer so that suffice for me. 

My issue is not converting to signed to unsigned but the type I wanted to use, since unsigned INT(10) can have value the exceeded Java's Int. JDBC's get{type}() does not give me that issue. It is just weird that before you use the get{type}(), the type is already known. I don't know how the driver works but maybe the library may need need adjustment on get{type} if Long is requested by the client and Int is in the driver, the library can safely convert it to Long.

**Comment by oshai** [comment]
You can see the actual types of mysql here: https://dev.mysql.com/doc/refman/8.0/en/integer-types.html
Int(10) unsigned is in the size of int (4 bytes) and unsigned: https://stackoverflow.com/questions/10879345/what-is-the-maximum-size-of-int10-in-mysql

The driver gets back from MySQL the type of the col and then decide what type to create for you. In that case, it will create an int (since it's unaware of it being unsigned). Since Java don't have unsigned types I suggest to take the value and convert it to long as suggested above.

Hope that is more clear.

**Comment by coud** [comment]
Yes I understand. So I tried to input 4294967295 value in an unsigned int(10) column and use getInt(), get() and getAs() to see how the driver behaves if value exceeded an Integer type. The result is I got an Integer with -1 value. I expected that in getInt() but with get() it still enforces to Integer which we can consider this a bug. getAs&lt;<Long>() also results in -1.

**Comment by oshai** [comment]
I think the best we can do at the moment is to document it so people will know what to expect.

**Comment by oshai** [comment]
I documented it here: https://stackoverflow.com/questions/55159687/why-mysql-int10-unsigned-column-to-row-getlong-throws-exception-in-jasync-sql/55159688
