### ISSUE TITLE
Any query causes BufferNotFullyConsumedException

### ISSUE THREAD

**Issue by Frederikam** [jasync-sql/jasync-sql#134]
Hello,

I am trying to migrate a small project from JDBC to R2DBC using this project's MySQL driver. When deploying to production I am having issues executing any queries at all, as I am getting this exception:

```
com.github.jasync.sql.db.exceptions.BufferNotFullyConsumedException: Buffer was not fully consumed by decoder, 39 bytes to read
        at com.github.jasync.sql.db.mysql.codec.MySQLFrameDecoder.doDecoding(MySQLFrameDecoder.kt:193) ~[jasync-mysql-1.0.2.jar!/:na]
        at com.github.jasync.sql.db.mysql.codec.MySQLFrameDecoder.handleCommonFlow(MySQLFrameDecoder.kt:158) ~[jasync-mysql-1.0.2.jar!/:na]
        at com.github.jasync.sql.db.mysql.codec.MySQLFrameDecoder.decode(MySQLFrameDecoder.kt:94) ~[jasync-mysql-1.0.2.jar!/:na]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) ~[netty-transport-native-epoll-4.1.36.Final-linux-x86_64.jar!/:4.1.36.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:432) ~[netty-transport-native-epoll-4.1.36.Final-linux-x86_64.jar!/:4.1.36.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[netty-transport-native-epoll-4.1.36.Final-linux-x86_64.jar!/:4.1.36.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-common-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.36.Final.jar!/:4.1.36.Final]
        at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
```

I was getting this exception on my local machine previously, but it somehow disappeared after recreating the database's docker image.

Example code:

```kotlin
client.execute().sql("SELECT @@VERSION;")
                .fetch()
                .all()
                .subscribe(System.out::println)
```

The `client` is a `DatabaseClient` provided by Spring, and is based off of this configuration:

```kotlin
override fun connectionFactory(): ConnectionFactory {
     val configuration = URLParser.parseOrDie(props.dbUrl, StandardCharsets.UTF_8)
    return JasyncConnectionFactory(MySQLConnectionFactory(configuration))
}
```

The MySQL version in both production and on my local machine is 8.0.12, as provided from the latest docker image. My version of `jasync-r2dbc-mysql` is 1.0.2.

**Comment by oshai** [comment]
There is an issue from the old driver that might be related (already fixed): https://github.com/mauricio/postgresql-async/issues/37

So it might be related to authentication somehow.
The best alternative is to provide a way to reproduce it (like a repo with docker that reproduce it). Otherwise trace logs might also be helpful (setting com.github.jasync.sql to trace on one instance).

**Comment by Frederikam** [comment]
I did some further testing and found that my remote docker container (in prod) produces the same exception when connecting from my laptop. To reiterate, the containers should both have the same configuration, and I am still not able to reproduce it locally.

If you would like to debug this yourself, I can set you up with an unprivileged database user.

**Comment by oshai** [comment]
If you can set log level to trace as mentioned above and share the logs it might help.

**Comment by Frederikam** [comment]
Here you go. Not sure it contains anything useful. 
https://gist.githubusercontent.com/Frederikam/5e76b97cd086442965a002d4b5b44e84/raw/cd1f5685fe5ee7356a52396b5e9fb2197f3741ef/trace.txt

**Comment by oshai** [comment]
It looks like logs are not in trace level for jasync. maybe because of compact logger name: `c.g.jasync.sql.db.mysql.MySQLConnection`. So try to enable that. In addition, I created a new version with an improved message for the exception that will give some more details: `1.0.3`.

**Comment by Frederikam** [comment]
So it turns out that the buffer exception was misleading. The actual error was that MySQL was not authenticating the connection for some reason, even though the user/password combination was correct.

MySQL's auth system is rather arcane to me. I have no idea why JDBC would still be working. The bad authentication configuration must have come from updating the docker container, as I have never changed it beyond setting a custom password.

**Comment by oshai** [comment]
So it turns out to be related to the issue above. If there is a way that I can reproduce it locally I might be able to improve the error message.

**Comment by Frederikam** [comment]
I thought that you had changed the exception handling so that it would relay the rejection message from mysql rather than throwing that `BufferNotFullyConsumedException`. That doesn't seem to be the case when looking at https://github.com/jasync-sql/jasync-sql/commit/752cfdaaf7a1f21221f2515f27c42b12e372f387

Once again, I have no idea how to reproduce it.

**Comment by hungphamchanh** [comment]
Hi @freyacodes  @oshai Is there any fixes or workaround to handle the situation ? I'm having the same problem with MySQL when connecting PROD. 
BufferNotFullyConsumedException: Buffer was not fully consumed by decoder

Below is the trace logging, don't know if It can help.

https://pastebin.com/UaRJ8mzt
(Please ignore the sentry warning)
