### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by unlimitedcoder2** [jasync-sql/jasync-sql#227]
When trying to use this library I am getting an error saying
```log
[21:50:14] [DefaultDispatcher-worker-1/WARN]: [DefaultDispatcher-worker-1] WARN com.github.jasync.sql.db.pool.ActorBasedObjectPool - uncaught Throwable
[21:50:14] [DefaultDispatcher-worker-1/WARN]: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at io.netty.util.internal.logging.Slf4JLoggerFactory.newInstance(Slf4JLoggerFactory.java:47)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:88)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:81)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at io.netty.bootstrap.Bootstrap.<clinit>(Bootstrap.java:51)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at com.github.jasync.sql.db.mysql.codec.MySQLConnectionHandler.<init>(MySQLConnectionHandler.kt:67)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at com.github.jasync.sql.db.mysql.MySQLConnection.<init>(MySQLConnection.kt:70)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at com.github.jasync.sql.db.mysql.MySQLConnection.<init>(MySQLConnection.kt:51)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at com.github.jasync.sql.db.mysql.pool.MySQLConnectionFactory.create(MySQLConnectionFactory.kt:32)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at com.github.jasync.sql.db.pool.ObjectPoolActor.createObject(ActorBasedObjectPool.kt:507)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at com.github.jasync.sql.db.pool.ObjectPoolActor.createNewItemPutInWaitQueue(ActorBasedObjectPool.kt:491)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at com.github.jasync.sql.db.pool.ObjectPoolActor.handleTake(ActorBasedObjectPool.kt:463)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at com.github.jasync.sql.db.pool.ObjectPoolActor.onReceive(ActorBasedObjectPool.kt:229)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at com.github.jasync.sql.db.pool.ActorBasedObjectPool$actor$1.invokeSuspend(ActorBasedObjectPool.kt:147)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[21:50:14] [DefaultDispatcher-worker-1/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

I added  `compile 'org.slf4j:slf4j-simple:1.7.22'` to my build.gradle which made it log the above error. And know that LoggerFactory is being shaded into the jar as I am able to use it.
```java
LoggerFactory.getLogger(this.getClass()).info("Test");
Connection connection = MySQLConnectionBuilder.createConnectionPool("jdbc:mysql://127.0.0.1:3306/charms?user=root&password=password");
try {
  QueryResult result = connection.sendQuery("select * from users;").get();
  for(RowData row: result.getRows()) {
    getLogger().info(row.getString("uuid"));
  }
} catch (InterruptedException | ExecutionException e) {
  e.printStackTrace();
}
```
Any idea why I might be facing this issue?

**Comment by oshai** [comment]
slf4j is not shaded, it's an implementation dependency. try to check dependency tree to understand why it's missing. also, what version of jasymc are you using?

**Comment by unlimitedcoder2** [comment]
`slf4j is not shaded, it's an implementation dependency` I have added `slf4j-simple` to my build.gradle so that it is shaded and I am able to use it. And I am using `jasync-mysql:1.1.6`

**Comment by oshai** [comment]
If you can share a small repo to reproduce it I might be able to assist more.

**Comment by unlimitedcoder2** [comment]
in this [repo](https://github.com/unlimitedcoder2test/spigot-kotlin-plugin-example) there are two folders, one is using maven and kotlin and the other is using java and gradle. I'm using [spigot](http://spigotmc.org/) to load this as a plugin.

**Comment by oshai** [comment]
does it happen in the gradle or maven module?
As a workaround I think you can add slf4j api dsependency.

**Comment by unlimitedcoder2** [comment]
it happens with both. I tried adding slf4j-api but still had the same issue as before

**Comment by oshai** [comment]
Can you please also try the solution here: https://stackoverflow.com/a/25621130/411965 ?

**Comment by unlimitedcoder2** [comment]
```log
[16:11:53] [Server thread/INFO]: [TestPlugin] Enabling TestPlugin v1.0
[16:11:53] [Server thread/WARN]: log4j:WARN No appenders could be found for logger (bz.ene.plugintest.Main).
[16:11:53] [Server thread/WARN]: log4j:WARN Please initialize the log4j system properly.
[16:11:53] [Server thread/WARN]: log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
>pl
>
```
I tried that but log4j is not setup so it couldn't get a logger from it

**Comment by oshai** [comment]
ok, that is a progress.
Try to setup logging like here: https://www.baeldung.com/slf4j-with-log4j2-logback

**Comment by oshai** [comment]
And also this: https://howtodoinjava.com/log4j2/log4j-2-xml-configuration-example/

**Comment by unlimitedcoder2** [comment]
It logs the same error again. It seems to be able to create a slf4j logger to log the errors and some info ```log
[23:15:58] [Server thread/INFO]: jasync available transport - native (epoll)
[23:15:59] [Server thread/INFO]: registering pool for periodic connection tests com.github.jasync.sql.db.pool.ActorBasedObjectPool@5ef4400f - PoolConfiguration(maxObjects=1, maxIdle=60000, maxQueueSize=2147483647, validationInterval=5000, createTimeout=5000, testTimeout=5000, queryTimeout=null, coroutineDispatcher=Dispatchers.Default, maxObjectTtl=null)
``` as it only logs them when `slf4j-simple` or the `slf4j-log4j` are added, but it fails to find the LoggerFactory in somewhere.

**Comment by unlimitedcoder2** [comment]
any update on this @oshai ?

**Comment by oshai** [comment]
I am sorry, but I need better instructions how to reproduce that.
I downloaded the project from: https://github.com/unlimitedcoder2test/spigot-kotlin-plugin-example
But I don't know what to run to reproduce it.
Trying to build it worked, I created a main method in Main class and it failed to load the class.
Also, I noticed `PluginClassLoader` which might indicate where the problem comes from.
Bottom line is that I need more info in order to assist, but it doesn't looks like caused by jasync-sql.

**Comment by unlimitedcoder2** [comment]
to run it you need to build [spigot](https://www.spigotmc.org/wiki/buildtools/) using `java -jar BuildTools.jar --rev 1.16.5` and then run it, accept the eula and put the jar from the project in the plugins directory. What could be happening with this `PluginClassLoader`?

**Comment by oshai** [comment]
The problem with classloaders is that sometimes it has visibility issues when the jars are not loaded from the same class loader. You can read more about it here: https://www.baeldung.com/java-classloaders#visibility. So more specifically is that it might be that the plugin jars lib has slf4j simple while the parent class loader has only slf4j api jar. Usually the simple workaround is to put all relevant jars in the parent classloader path (slf4j simple in that case). But that is a guess, try to list all jars in both directories.

**Comment by unlimitedcoder2** [comment]
so I should add slf4j-simple to my classpath?

**Comment by unlimitedcoder2** [comment]
You mentioned that `PluginClassLoader` could be causing the error, do you know what the solution to this could be?

**Comment by unlimitedcoder2** [comment]
Commenting out this line fixed the issue for me [link](https://github.com/jasync-sql/jasync-sql/blob/master/db-async-common/src/main/java/com/github/jasync/sql/db/util/NettyUtils.kt#L30)
