### ISSUE TITLE
com.github.jasync.sql.db.exceptions.DatabaseException: Connection is being closed

### ISSUE THREAD

**Issue by brminato** [jasync-sql/jasync-sql#238]
Hi. I´m running a application in production with Spring WebFlux and Jasync. The application works fine **BUT** sometimes the application prints a error:

exception: com.github.jasync.sql.db.exceptions.DatabaseException: Connection is being closed
logger: reactor.core.publisher.Operators
message: Operator called default onErrorDropped

I could only reproduce the same behavior locally when I execute a stress test with JMeter calling a simple API GET and stop the requests after a while causing the problem. If I don´t stop the application works fine. Does anyone already had the same problem?

**Database configuration:**
spring.r2dbc.url=r2dbc:pool:mysql://localhost:3306/test
spring.r2dbc.username=xxx
spring.r2dbc.password=xxxx
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.max-idle-time=30m
spring.r2dbc.pool.validation-query: SELECT 1

**Code:** 

`public Mono<User> get2() {
		return this.databaseClient
                .sql("SELECT * FROM users WHERE id=:id")
                .bind("id", 1)
                .map(MAPPING_FUNCTION)
                .one();
	}`
	
**More details**

` exception: com.github.jasync.sql.db.exceptions.DatabaseException: Connection is being closed
	at com.github.jasync.sql.db.mysql.MySQLConnection.close(MySQLConnection.kt:120)
	at com.github.jasync.sql.db.mysql.MySQLConnection.disconnect(MySQLConnection.kt:313)
	at com.github.jasync.r2dbc.mysql.JasyncClientConnection$close$1.get(JasyncClientConnection.kt:87)
	at com.github.jasync.r2dbc.mysql.JasyncClientConnection$close$1.get(JasyncClientConnection.kt:18)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97)
	at reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1829)`

**Comment by sshark** [comment]
I have seen a similar exception with other drivers, r2dbc-mysql. My db has a global timeout of 3 mins and even though I set my `spring.r2dbc.pool.max-idle-time=2s` I still see the connection exception,

```
2021-06-28 10:09:55,088 ERROR reactor.core.publisher.Operators [reactor-tcp-epoll-3] Operator called default onErrorDropped   
dev.miku.r2dbc.mysql.client.MySqlConnectionClosedException: Connection closed   
               at dev.miku.r2dbc.mysql.client.ClientExceptions.expectedClosed(ClientExceptions.java:36) 
               at dev.miku.r2dbc.mysql.client.ReactorNettyClient.handleClose(ReactorNettyClient.java:262)
               at dev.miku.r2dbc.mysql.client.ReactorNettyClient.access$400(ReactorNettyClient.java:53) 
               at dev.miku.r2dbc.mysql.client.ReactorNettyClient$ResponseSubscriber.onComplete(ReactorNettyClient.java:306)  
...
```

**Comment by oshai** [comment]
My guess would be that this in an `r2dbc:pool` issue. Try to see what version you're using, maybe it's a known issue, and if not try to report it there.
