### ISSUE TITLE
channelFactory set already

### ISSUE THREAD

**Issue by wind-hx** [jasync-sql/jasync-sql#256]
java.lang.IllegalStateException: channelFactory set already
	at io.netty.bootstrap.AbstractBootstrap.channelFactory(AbstractBootstrap.java:121)
	at io.netty.bootstrap.AbstractBootstrap.channelFactory(AbstractBootstrap.java:137)
	at io.netty.bootstrap.AbstractBootstrap.channel(AbstractBootstrap.java:109)
	at com.github.jasync.sql.db.mysql.codec.MySQLConnectionHandler.connect(MySQLConnectionHandler.kt:84)
	at com.github.jasync.sql.db.mysql.MySQLConnection.connect(MySQLConnection.kt:116)
	at com.wind.telegram.framework.asyncdao.mysql.pool.ConnectionPool.getConnection(ConnectionPool.java:68)
	at com.wind.telegram.framework.asyncdao.proxy.MapperProxy.getConnection(MapperProxy.java:218)
	at com.wind.telegram.framework.asyncdao.proxy.MapperProxy.execute(MapperProxy.java:231)
	at com.wind.telegram.framework.asyncdao.proxy.MapperProxy.invoke(MapperProxy.java:83)
	at com.sun.proxy.$Proxy42.queryById(Unknown Source)
	at com.wind.telegram.schedule.job.MessageSchedule.send(MessageSchedule.java:47)
	at com.wind.telegram.schedule.job.JobHandler.sendMessageJobHandler(JobHandler.java:37)
	at jdk.internal.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:31)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:163)

**Comment by wind-hx** [comment]
`
public void getConnection(Handler<AsyncResult<SQLConnection>> handler) {
        Connection connection = null;
        try {
            connection = pool.borrowObject(borrowMaxWaitMillis);
        } catch (Exception e) {
            handler.handle(Future.failedFuture(e));
        }
        if (Objects.isNull(connection)) {
            handler.handle(Future.failedFuture("Connection is close"));
            return;
        }
        if (connection.isConnected()) {
            handler.handle(Future.succeededFuture(new AsyncSQLConnectionImpl(connection, this, executionContext)));
        } else {
            connection.connect().whenComplete((BiConsumer<Connection, Throwable>) (conn, throwable) -> {
                if (null != throwable) {
                    handler.handle(Future.failedFuture(throwable));
                } else {
                    handler.handle(Future.succeededFuture(new AsyncSQLConnectionImpl(conn, this, executionContext)));
                }
            });
        }
    }
`

**Comment by wind-hx** [comment]
``` java
public void getConnection(Handler<AsyncResult<SQLConnection>> handler) {
        Connection connection = null;
        try {
            connection = pool.borrowObject(borrowMaxWaitMillis);
        } catch (Exception e) {
            handler.handle(Future.failedFuture(e));
        }
        if (Objects.isNull(connection)) {
            handler.handle(Future.failedFuture("Connection is close"));
            return;
        }
        if (connection.isConnected()) {
            handler.handle(Future.succeededFuture(new AsyncSQLConnectionImpl(connection, this, executionContext)));
        } else {
            connection.connect().whenComplete((BiConsumer<Connection, Throwable>) (conn, throwable) -> {
                if (null != throwable) {
                    handler.handle(Future.failedFuture(throwable));
                } else {
                    handler.handle(Future.succeededFuture(new AsyncSQLConnectionImpl(conn, this, executionContext)));
                }
            });
        }
    }
```

**Comment by wind-hx** [comment]
connection.connect()
error

**Comment by oshai** [comment]
I am not sure why this happens but if you can provide trace logging it might be helpful.

**Comment by wind-hx** [comment]
I found the problem,Because of the asynchronous connection, connection.connect() is called multiple times.

**Comment by wind-hx** [comment]
When a connection is connecting, call connect() again

**Comment by wind-hx** [comment]
Asynchronous connection plus a connection status is solved

**Comment by wind-hx** [comment]
> I am not sure why this happens but if you can provide trace logging it might be helpful.

This error occurs when the network is not good, and the connection is reconnected after the connection is disconnected.

**Comment by wind-hx** [comment]
https://github.com/jasync-sql/jasync-sql/pull/260
