### ISSUE TITLE
Operation timeout after it took too long to return (PT1M)

### ISSUE THREAD

**Issue by wind-hx** [jasync-sql/jasync-sql#257]
java.util.concurrent.TimeoutException: Operation timeout after it took too long to return (PT1M)
        at com.github.jasync.sql.db.pool.TimeoutSchedulerImpl$addTimeout$1$scheduledFuture$1.invoke(TimeoutScheduler.kt:63) [telegram-schedule.jar:?]
        at com.github.jasync.sql.db.pool.TimeoutSchedulerImpl$addTimeout$1$scheduledFuture$1.invoke(TimeoutScheduler.kt:31) [telegram-schedule.jar:?]
        at com.github.jasync.sql.db.pool.TimeoutSchedulerImpl$schedule$1.run(TimeoutScheduler.kt:51) [telegram-schedule.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [telegram-schedule.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) [telegram-schedule.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [telegram-schedule.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [telegram-schedule.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [telegram-schedule.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [telegram-schedule.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [telegram-schedule.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by oshai** [comment]
looks like a 1m timeout as configured to your query timeout. Try to increase the timeout because your query takes longer.

Looks like a normal way of work.
