### ISSUE TITLE
java.time.OffsetDateTime Support in 2.0.x with Timestamp(z)

### ISSUE THREAD

**Issue by KevinAtSesam** [jasync-sql/jasync-sql#261]
Hey,

When updating from 1.2.3 to 2.0.2, all existing testcode fails with the following message.

```
Failed to retrieve value because Please send a feedback to the library maintainers about supporting class java.time.OffsetDateTime for #timestamp!. If you're using SQLInterpolation, you may mistake u.id for u.resultName.id.

scalikejdbc.ResultSetExtractorException: Failed to retrieve value because Please send a feedback to the library maintainers about supporting class java.time.OffsetDateTime for #timestamp!. If you're using SQLInterpolation, you may mistake u.id for u.resultName.id.
	at scalikejdbc.WrappedResultSet.wrapIfError(WrappedResultSet.scala:28)
	at scalikejdbc.WrappedResultSet.get(WrappedResultSet.scala:479)
	at scalikejdbc.WrappedResultSet.offsetDateTimeOpt(WrappedResultSet.scala:449)
	at com.sesamsolutions.platform.accountmgmt.db.AccountRecord$.toAccount(AccountDatabaseModel.scala:51)
	at com.sesamsolutions.platform.accountmgmt.db.AccountDao.$anonfun$getAccount$1(AccountDao.scala:102)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
	at scala.collection.immutable.List.prependedAll(List.scala:153)
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1251)
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1251)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1288)
	at scalikejdbc.async.AsyncDBSession.$anonfun$iterable$2(AsyncDBSession.scala:97)
	at scala.Option.map(Option.scala:242)
	at scalikejdbc.async.AsyncDBSession.$anonfun$iterable$1(AsyncDBSession.scala:96)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Since you're specifically asking for it, I figured it would be good to get in contact with you. Is there any way how I can assist in this case, or is this just something you plan to add in the future?

**Comment by oshai** [comment]
Thanks for reporting. 
Can you please provide more details, like the query and the table? 
I am not sure what exactly went wrong and the stacktrace doesn't  contain any jasync frame.

**Comment by KevinAtSesam** [comment]
I'm sorry for keeping you waiting. Had some high-priority issues that kept me busy.

A part of the problem could be that I define Jasync-sql independently from scalikejdbc-async, which still uses 1.2.3 in the current package. So that might be related. Here are the actual code-snippets, minus some omissions for business reasons. I did keep all the date-time fields so you can see their process flow.

#### build.sbt
```
// For async database logic and migration
val postgresql = "org.postgresql" % "postgresql" % "42.2.23"
val postgresqlAsync = "com.github.jasync-sql" % "jasync-postgresql" % "2.0.2"

val scalikejdbc = "org.scalikejdbc" %% "scalikejdbc-async" % "0.14.0"
val scalikejdbcTest = "org.scalikejdbc" %% "scalikejdbc-test" % "3.5.0" % "test"
val scalikejdbcConfig = "org.scalikejdbc" %% "scalikejdbc-config" % "3.5.0"
val scalikejdbcSyntaxSupport = "org.scalikejdbc" %% "scalikejdbc-syntax-support-macro" % "3.5.0"
```

#### AccountDAO
```
 def getAccount(accountId: Id[Account])(implicit tc: TransactionContext): Future[Option[Account]] = {
    withSQL {
      select(A.result.*)
        .from(AccountRecord as A)
        .where
        .eq(A.id, accountId)
    }.map(AccountRecord.toAccount(A.resultName))
  }.single().future()
```

#### AccountRecord
```

case class AccountRecord(
  id: Long,
  firstName: String,
  lastName: String,
  email: String,
  phone: String,
  [...]
  dateCreated: OffsetDateTime,
  dateModified: OffsetDateTime,
  [...]
  dateLastAuthentication: OffsetDateTime,
  dateCleanNotification: OffsetDateTime
)

object AccountRecord extends SQLSyntaxSupport[AccountRecord] {

  override def tableName: String = "accounts"

  override def columns: collection.Seq[String] = autoColumns[AccountRecord]()

  def toAccount(g: ResultName[AccountRecord])(rs: WrappedResultSet): Account = {
    Account(
      id = Id[Account](rs.get(g.id)),
      firstName = rs.stringOpt(g.firstName),
      lastName = rs.stringOpt(g.lastName),
      phone = PhoneNumber(rs.string(g.phone)),
      [...]
      dateCreated = rs.offsetDateTimeOpt(g.dateCreated),
      dateModified = rs.offsetDateTimeOpt(g.dateModified),
      [...]
      dateLastAuthentication = rs.offsetDateTimeOpt(g.dateModified),
      dateCleanNotification = rs.offsetDateTimeOpt(g.dateModified)
    )
  }
}
```

**Comment by oshai** [comment]
It seems to me that this is an issue with `scalikejdbc-async`.  
I suggest to upgrade jasync to 2.x on scalike and open an issue there for that.
