### ISSUE TITLE
MySQL connections maxing out resulting in Too many connection error on invalid credential

### ISSUE THREAD

**Issue by sushilnayak** [jasync-sql/jasync-sql#329]
We recently had encountered and issue where invalid/expired credential were used to deploy single instance of our microservice using kotlin and aurora mysql in our test environment.

While trying to validate the deployment, we started seeing too many request error. Interestingly the r2dbc pool had been set to max 20 connections, but our microservice formed more than 500 connections( maximum connection db could take). At db end, the wait for connection timeout parameter was set to 8 hours and thats when connection dropping starts to happen, but during hte 8 hours nobody is able to acccess the DB.

So, DB connections are not released by jasync when invalid credential is entered. To confirm this was issue related to jasync only, i tried to use dev.miku mysql r2dbc driver and there connection does not go beyond 20 and connections are released quickly. It seems jasync does not drop connection if AuthenticationError is recieved. Interestingly the exception jasync is throwing is **UnsupportedAuthenticationMethodException : Unknown authentication method -> 'caching_sha2_password'**

**Comment by oshai** [comment]
Hi,
`caching_sha2_password` is not supported ATM (see #297). Are you sure this is a case of bad credentials and not Unknown authentication method? Is there a stacktrace you can share?

**Comment by oshai** [comment]
If you can upload your winfows repo with instructions I can try it on my mac.

**Comment by sushilnayak** [comment]
@oshai , here is the repo https://github.com/sushilnayak/spring-kotlin-r2dbc-jasync which i created on my windows machine which is giving me expected result( AccessDenied Exception resulting in closing of connections). I cloned the code on my office mac laptop and connected to mysql:8 docker container w/ incorrect password and sadly getting **com.github.jasync.sql.db.exceptions.UnsupportedAuthenticationMethodException: Unknown authentication method -> 'caching_sha2_password'** . 

The only difference im doing at home vs office is, in office i'm connecting to mysql:8 docker container and at home im connecting to aurora mysql db. It shouldn't matter coz IT test are going to use docker container. And the other difference is the running environment i.e mac vs windows

**Comment by oshai** [comment]
I am pretty sure the error you see is because of using mysql 8. See #297 and [other issues](https://github.com/jasync-sql/jasync-sql/search?q=caching_sha2_password&type=issues) like #239.

**Comment by sushilnayak** [comment]
The aurora mysql instance i tested the code on was mysql 8.0.28 and docker mysql image is also 8. Windows shows excepted result( i.e. connection closing frequently ), while running on mac shows different result. 

I would have agreed it to be mysql 8 issue, but we are getting AccessDenied Exception on Windows machine which is correct. Running app on mac shows different result from windows when incorrect password is entered in app. I'll probably run this again using aurora in office and check the erorr log from mysql.

**Comment by oshai** [comment]
It might be that the plugin fails to load on windows or something else that cause such fallback: https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded

**Comment by sushilnayak** [comment]
Hey @oshai, I checked and looks like the stackoverflow error is not related to this issue. 

In both cases, windows and mac. application connecting successfully with correct credential. The difference are with incorrect credentials only. Where mac is thowing caching_sha2_password **UnsupportedAuthenticationMethodException** and causing connection to max out on db letting other logins to db getting **Too many request** error. 

Were you able to run the code i gave on your mac. Did you get the same UnsupportedAuthenticationMethodException exception and connection maxing out at your end?

**Comment by oshai** [comment]
I was able to run the repo, and the exception is different for mysql 5 vs 8, but this is expected.
In 8:
```
io.netty.handler.codec.EncoderException: com.github.jasync.sql.db.exceptions.UnsupportedAuthenticationMethodException: Unknown authentication method -> 'caching_sha2_password'
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:102) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at com.github.jasync.sql.db.mysql.codec.MySQLConnectionHandler.writeAndHandleError(MySQLConnectionHandler.kt:417) ~[jasync-mysql-2.0.6.jar:na]
        at com.github.jasync.sql.db.mysql.codec.MySQLConnectionHandler.write(MySQLConnectionHandler.kt:280) ~[jasync-mysql-2.0.6.jar:na]
        at com.github.jasync.sql.db.mysql.MySQLConnection.onHandshake(MySQLConnection.kt:295) ~[jasync-mysql-2.0.6.jar:na]
        at com.github.jasync.sql.db.mysql.codec.MySQLConnectionHandler.channelRead0(MySQLConnectionHandler.kt:115) ~[jasync-mysql-2.0.6.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: com.github.jasync.sql.db.exceptions.UnsupportedAuthenticationMethodException: Unknown authentication method -> 'caching_sha2_password'
        at com.github.jasync.sql.db.mysql.encoder.HandshakeResponseEncoder.encode(HandshakeResponseEncoder.kt:33) ~[jasync-mysql-2.0.6.jar:na]
        at com.github.jasync.sql.db.mysql.codec.MySQLOneToOneEncoder.encode(MySQLOneToOneEncoder.kt:67) ~[jasync-mysql-2.0.6.jar:na]
        at com.github.jasync.sql.db.mysql.codec.MySQLOneToOneEncoder.encode(MySQLOneToOneEncoder.kt:23) ~[jasync-mysql-2.0.6.jar:na]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        ... 35 common frames omitted
```
while in 5
```
org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection; nested exception is com.github.jasync.sql.db.mysql.exceptions.MySQLException: Error 1045 - #28000 - Access denied for user 'root'@'172.17.0.1' (using password: YES)
        at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:88) ~[spring-r2dbc-5.3.23.jar:5.3.23]
        at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3776) ~[reactor-core-3.4.23.jar:3.4.23]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.4.23.jar:3.4.23]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.4.23.jar:3.4.23]
        at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:95) ~[reactor-core-3.4.23.jar:3.4.23]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172) ~[reactor-core-3.4.23.jar:3.4.23]
        at reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:475) ~[reactor-pool-0.2.9.jar:0.2.9]
        at reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:431) ~[reactor-pool-0.2.9.jar:0.2.9]
        at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186) ~[reactor-core-3.4.23.jar:3.4.23]
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121) ~[reactor-core-3.4.23.jar:3.4.23]
        at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.23.jar:3.4.23]
        at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.4.23.jar:3.4.23]
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:219) ~[reactor-core-3.4.23.jar:3.4.23]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142) ~[reactor-core-3.4.23.jar:3.4.23]
        at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:89) ~[reactor-core-3.4.23.jar:3.4.23]
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[na:na]
        at com.github.jasync.sql.db.util.FutureUtilsKt.failed(FutureUtils.kt:18) ~[jasync-pool-2.0.6.jar:na]
        at com.github.jasync.sql.db.mysql.MySQLConnection.setException(MySQLConnection.kt:196) ~[jasync-mysql-2.0.6.jar:na]
        at com.github.jasync.sql.db.mysql.MySQLConnection.onError(MySQLConnection.kt:191) ~[jasync-mysql-2.0.6.jar:na]
        at com.github.jasync.sql.db.mysql.codec.MySQLConnectionHandler.channelRead0(MySQLConnectionHandler.kt:123) ~[jasync-mysql-2.0.6.jar:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.23.jar:3.4.23]
                at reactor.core.publisher.Mono.block(Mono.java:1707) ~[reactor-core-3.4.23.jar:3.4.23]
                at com.nayak.springkotlinr2dbcsample.RandomService.firstScheduledQuery(SpringKotlinR2dbcSampleApplication.kt:39) ~[classes/:na]
                at com.nayak.springkotlinr2dbcsample.RandomService$$FastClassBySpringCGLIB$$c21b5e1a.invoke(<generated>) ~[classes/:na]
                at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.23.jar:5.3.23]
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.23.jar:5.3.23]
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.23.jar:5.3.23]
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.23.jar:5.3.23]
                at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.3.23.jar:5.3.23]
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
                ... 1 common frames omitted
```
From the server perspective it seems that this is not exhausting the server connections (didn't reproduce the too many connections):
```
+-------------------------------------------------------+---------------------+
| Variable_name                                         | Value               |
+-------------------------------------------------------+---------------------+
| Aborted_connects                                      | 2717                |
| Connection_errors_accept                              | 0                   |
| Connection_errors_internal                            | 0                   |
| Connection_errors_max_connections                     | 0                   |
| Connection_errors_peer_address                        | 0                   |
| Connection_errors_select                              | 0                   |
| Connection_errors_tcpwrap                             | 0                   |
| Connections                                           | 2765                |
| Global_connection_memory                              | 0                   |
| Locked_connects                                       | 0                   |
| Max_used_connections                                  | 45                  |
| Max_used_connections_time                             | 2022-10-29 20:44:39 |
| Mysqlx_connection_accept_errors                       | 0                   |
| Mysqlx_connection_errors                              | 0                   |
| Mysqlx_connections_accepted                           | 0                   |
| Mysqlx_connections_closed                             | 0                   |
| Mysqlx_connections_rejected                           | 0                   |
| Performance_schema_session_connect_attrs_longest_seen | 113                 |
| Performance_schema_session_connect_attrs_lost         | 0                   |
| Ssl_client_connects                                   | 0                   |
| Ssl_connect_renegotiates                              | 0                   |
| Ssl_finished_connects                                 | 0                   |
| Threads_connected                                     | 41                  |
+-------------------------------------------------------+---------------------+
23 rows in set (0.00 sec)

mysql> show variables like "max_connections";
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 151   |
+-----------------+-------+
1 row in set (0.00 sec)



mysql> show status where `variable_name` = 'Threads_connected';
+-------------------+-------+
| Variable_name     | Value |
+-------------------+-------+
| Threads_connected | 41    |
+-------------------+-------+
1 row in set (0.00 sec)



mysql> 
```
Note that `Threads_connected` is number of active connections as [here](https://stackoverflow.com/questions/7432241/mysql-show-status-active-or-total-connections).

Another this you can try is to inspect the open connections like this:
```
mysql> show processlist;
+------+----------------------+------------------+------+---------+------+------------------------+------------------+
| Id   | User                 | Host             | db   | Command | Time | State                  | Info             |
+------+----------------------+------------------+------+---------+------+------------------------+------------------+
|    5 | event_scheduler      | localhost        | NULL | Daemon  | 3195 | Waiting on empty queue | NULL             |
|  953 | root                 | localhost        | NULL | Query   |   16 | init                   | show processlist |
| 4040 | unauthenticated user | 172.17.0.1:65080 | NULL | Connect |   19 | Sending to client      | NULL             |
| 4048 | unauthenticated user | 172.17.0.1:65098 | NULL | Killed  |   17 | login                  | NULL             |
| 4081 | unauthenticated user | 172.17.0.1:57370 | NULL | Connect |    9 | Sending to client      | NULL             |
| 4082 | unauthenticated user | 172.17.0.1:57372 | NULL | Connect |    8 | Sending to client      | NULL             |
+------+----------------------+------------------+------+---------+------+------------------------+------------------+
6 rows in set (16.40 sec)
```
you might be able to see what's holding active connections like that.

**Comment by sushilnayak** [comment]
Hi @oshai , i tried to run the code on mac, the same repo w/ docker mysql:8 image and im getting different result after running the code for 5 min. The **Thread_connected** increases to 152 and goes down slowly with log showing timeout and again come back to 152. I confirmed by no. of entries coming in processlist with condition **User = "unauthenticated user"** and that was same. Also, in the log i did find too many connection request error. Here is the log, check the trace from MySQLConnection

```
2022-10-30 17:04:56.019 TRACE 13424 --- [-netty-thread-1] c.g.j.s.d.mysql.codec.MySQLFrameDecoder  : got message type -1
2022-10-30 17:04:56.019 ERROR 13424 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-2713> Received an error message -> ErrorMessage(errorCode=1040, sqlState=Too ma, errorMessage=ny connections)
2022-10-30 17:04:56.019 TRACE 13424 --- [netty-thread-24] c.g.j.s.d.mysql.codec.MySQLFrameDecoder  : [connectionId:<mysql-connection-2712>] - Reading message type 10 - (count=1,hasDoneHandshake=false,size=74,isInQuery=false,processingColumns=false,processingParams=false,processedColumns=0,processedParams=0)
0: 0a 38 2e 30 2e 33 30 00     . 8 . 0 . 3 0 . 
1: e6 05 00 00 15 2e 33 25     . . . . . . 3 % 
2: 55 7c 5a 72 00 ff ff ff     U | Z r . . . . 
3: 02 00 ff df 15 00 00 00     . . . . . . . . 
4: 00 00 00 00 00 00 00 48     . . . . . . . H 
5: 2b 65 2d 0c 55 2a 66 3c     + e - . U * f < 
6: 3c 17 45 00 63 61 63 68     < . E . c a c h 
7: 69 6e 67 5f 73 68 61 32     i n g _ s h a 2 
8: 5f 70 61 73 73 77 6f 72 64 00     _ p a s s w o r d . 
Total 74 bytes read
}
```

**Comment by sushilnayak** [comment]
@oshai, were you able to look at the log i had provided earlier

**Comment by oshai** [comment]
I created an experimental fix in #332. If it possible for you to download the branch and try it that will be great. There are some unrelated issues there that I want to fix before submitting.

**Comment by sushilnayak** [comment]
@oshai , Thanks for the feature branch for fix, we are still working on testing this. Will get back to you by next week on this.

**Comment by kartikarora2** [comment]
Hi @oshai 

The fix you provided does not seem to work. Also here are some observations we captured while implementing your fix into our code base

**Observation based on the logs**
The method (exceptionCaught()) where you have called disconnect() is called only when we are facing below exception.

`logger: com.github.jasync.sql.db.mysql.MySQLConnection
   message: <mysql-connection-2079> Transport failure 
stack_trace: com.github.jasync.sql.db.exceptions.BufferNotFullyConsumedException: Buffer was not fully consumed by decoder, 21 bytes to read, decoder is AuthenticationSwitchRequestDecoder and message is AuthenticationSwitchRequest
	at com.github.jasync.sql.db.mysql.codec.MySQLFrameDecoder.doDecoding(MySQLFrameDecoder.kt:215)
	at com.github.jasync.sql.db.mysql.codec.MySQLFrameDecoder.handleCommonFlow(MySQLFrameDecoder.kt:173)
	at com.github.jasync.sql.db.mysql.codec.MySQLFrameDecoder.decode(MySQLFrameDecoder.kt:99)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)`

But we are still seeing a lot of exceptions being related to "too many connections" being faced. 
`logger: com.github.jasync.sql.db.mysql.MySQLConnection
   message: <mysql-connection-27909> Received an error message -> ErrorMessage(errorCode=1040, sqlState=Too ma, errorMessage=ny connections)`

So it is possible that we should have called the disconnect method when onError() method is being invoked. And the number of error messages related to "Too many connections" is way higher than the "Transport failure"error message.

**Observations based on the connection count data fetched from mysql**
It is observed that the although with wrong credentials the connection count keeps on increasing until it reaches the max limit. But the connections are occupied are using the correct credentials. For ex for MySQL db instance if the 
correct credentials are - user1 and pwd1  
incorrect credentials are - user2 and pwd2 

For incorrect credentials we are getting below error

`logger: com.github.jasync.sql.db.mysql.MySQLConnection
   message: <mysql-connection-1943> Received an error message -> ErrorMessage(errorCode=1045, sqlState=#28000, errorMessage=Access denied for user 'user2'@'000.xxx.xx.xxx' (using password: YES))`

But if we run the below query, it is observed that all the connections are being occupied by threads with correct credentials user even though the if we have we have set the connection pool max pool size to be 20 all the connections are occupied upto the maximum allowed limit of the db instance. Also if you see the screenshot below, all the connections are in sleep state for a very long time and these connections are only released after the mysql **wait_timeout** is met that is 8hrs.


`SELECT * FROM INFORMATION_SCHEMA.PROCESSLIST`
<img width="1565" alt="Screenshot 2022-12-10 at 9 51 23 PM" src="https://user-images.githubusercontent.com/119792820/206864794-47aaa443-c759-44d0-abf6-05776f720f78.png">

**Comment by kartikarora2** [comment]
Hi @oshai 
I will update this at my end and will let you know. If this works out or not.

**Comment by kartikarora2** [comment]
Hi @oshai 
Disconnecting `onError()` also didn't work out. Can you please suggest what else can be done.

**Comment by oshai** [comment]
I don't have another idea other than implementing `caching_sha2_password` at the moment.

**Comment by KarboniteKream** [comment]
I'm implementing the support for `caching_sha2_password` in #358. It may help you investigate your issue. Please let me know if you have any issues with the new authentication mode, I'm still testing it.

**Comment by oshai** [comment]
Can you please try version 2.1.12?

**Comment by oshai** [comment]
@kartikarora2 did you had change to check it with version >= 2.1.12?

**Comment by kartikarora2** [comment]
Hi @oshai @KarboniteKream 
We are using AWS Aurora MySQL in our project, it still uses `mysql_native_password` for authentication. So this fix might not fix this issue?

**Comment by oshai** [comment]
> Hi @oshai @KarboniteKream We are using AWS Aurora MySQL in our project, it still uses `mysql_native_password` for authentication. So this fix might not fix this issue? Also, we are using spring boot version < 3, so we won't be able to apply these changes.

It might still fix the issue, as it was reporting auth method unimplemented, and now it is implemented.
