### ISSUE TITLE
sporadic NPE written to logs

### ISSUE THREAD

**Issue by oshai** [jasync-sql/jasync-sql#59]
Happened with version 0.8.52.
It usually looks like a bad connection, bursts of errors for couple of secdonds from the same connection, and then get back to normal (maybe connection is disposed).
this is the stacktrace:
kotlin.KotlinNullPointerException:
  at com.github.jasync.sql.db.mysql.codec.MySQLConnectionHandler.channelRead0(MySQLConnectionHandler.kt:143)
  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)
  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:299)
  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:415)
  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1304)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:921)
  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:135)
  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
  at java.lang.Thread.run(Thread.java:748)

**Comment by oshai** [comment]
Issue is fixed by above commits - - add 30 sec to timeout before cleaning up the object from the pool this will allow normal scheduler to trigger timeout and handle timeout before which is the preferred way because less errors are getting to the logs

**Comment by oshai** [comment]
Although fix reduced the errors it still happens, but now less often. Will add a fix to ignore those messages if the connection was closed.
