### ISSUE TITLE
java.util.NoSuchElementException: null

### ISSUE THREAD

**Issue by oshai** [jasync-sql/jasync-sql#63]
ObjectPool has 3 methods that currently not thread safe:
- futures in queue
- connections in use
- connections free

Currently, it is used for debugging and metrics.

They are not thread safe and might throw exceptions like the below:
```
Caused by: java.util.NoSuchElementException: null
	at java.util.WeakHashMap$HashIterator.nextEntry(WeakHashMap.java:808) [?:1.8.0_144]
	at java.util.WeakHashMap$KeyIterator.next(WeakHashMap.java:839) [?:1.8.0_144]
	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1152) [kotlin-stdlib-1.3.10.jar:1.3.10-release-253 (1.3.10)]
	at com.github.jasync.sql.db.pool.ObjectPoolActor.getUsedItemsList(ActorBasedObjectPool.kt:211) [jasync-common-0.8.57-netty4.0.jar:?]
	at com.github.jasync.sql.db.pool.ActorBasedObjectPool.getUsedItems(ActorBasedObjectPool.kt:151) [jasync-common-0.8.57-netty4.0.jar:?]
	at com.github.jasync.sql.db.pool.ConnectionPool.inUse(ConnectionPool.kt:107) [jasync-common-0.8.57-netty4.0.jar:?]
	at com.outbrain.ob1k.db.experimental.MySqlConnectionPool.lambda$new$2(MySqlConnectionPool.java:49) [ob1k-db-1.1.146.jar:?]
```

**Comment by oshai** [comment]
The solution is to add methods returning the size of collections instead of a copy of the collection
