### ISSUE TITLE
How to do singleton connect?

### ISSUE THREAD

**Issue by leenux** [jasync-sql/jasync-sql#77]
#### local var is ok
```
GlobalScope.async {
        val connection = PostgreSQLConnectionBuilder.createConnectionPool(
            "postgres://cherry@localhost:26257/cherry?user=***&password=***&sslmode=verify-full&sslrootcert=ca.crt&sslcert=client.cherry.crt&sslkey=client.cherry.key"
        )
        val queryResult = connection.sendPreparedStatement("select 0").get()
        connection.disconnect().get()
    }
```

#### But singleton got error
```
object DbOne {
    val Pool: ConnectionPool<PostgreSQLConnection>
        get() = PostgreSQLConnectionBuilder.createConnectionPool(
            url="postgres://cherry@localhost:26257/cherry?user=xxx&password=xxx&sslmode=verify-full&sslrootcert=ca.crt&sslcert=client.cherry.crt&sslkey=client.cherry.key"
        )
}
```
```
GlobalScope.async {
        val queryResult = DbOne.Pool.sendPreparedStatement("select 0").get()
    }
```
#### error log is
```
2019-01-12 19:35:26.322 [db-sql-netty-thread-1] ERROR c.g.j.s.d.p.PostgreSQLConnection - Error , message -> ErrorMessage(fields=[(Severity, ERROR), (SQLSTATE, 08P01), (File, sql/pgwire/pgwirebase/encoding.go), (Line, 189), (Routine, NewProtocolViolationErrorf), (Message, SimpleQuery not allowed while in extended protocol mode)])
2019-01-12 19:35:26.327 [db-sql-netty-thread-1] ERROR c.g.j.s.d.p.PostgreSQLConnection - Error on connection
com.github.jasync.sql.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=[(Severity, ERROR), (SQLSTATE, 08P01), (File, sql/pgwire/pgwirebase/encoding.go), (Line, 189), (Routine, NewProtocolViolationErrorf), (Message, SimpleQuery not allowed while in extended protocol mode)])
	at com.github.jasync.sql.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.kt:200)
	at com.github.jasync.sql.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.kt:197)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:748)
2019-01-12 19:35:26.328 [db-sql-netty-thread-1] ERROR c.g.j.s.d.p.PostgreSQLConnection - Setting error on future java.util.concurrent.CompletableFuture@79d2acf7[Not completed, 1 dependents]
2019-01-12 19:35:26.341 [db-sql-netty-thread-1] INFO  c.g.j.s.d.p.c.PostgreSQLConnectionHandler - Connection disconnected - localhost/127.0.0.1:26257
```
#### version
cockroachdb:2.1.3(=postgre 9.5)
jasync-postgresql:0.8.64

**Comment by oshai** [comment]
I will take a deeper look later, but one thing noticed: Since you're using `get()` it creates a new pool on each call.

**Comment by leenux** [comment]
Would it be better if I used  `await()`?

**Comment by oshai** [comment]
I think I was not clear enough.
```
val Pool: ConnectionPool<PostgreSQLConnection>
        get() = ...
```
The above is a getter, so each call to `DbOne.Pool` will create a new pool and not reuse the same one. So it is advised to replace that with either:
```
val Pool: ConnectionPool<PostgreSQLConnection> = PostgreSQLConnectionBuilder.createConnectionPool(
            url="postgres://cherry@localhost:26257/cherry?user=xxx&password=xxx&sslmode=verify-full&sslrootcert=ca.crt&sslcert=client.cherry.crt&sslkey=client.cherry.key"
        )
```
or if you want it to be lazy use the `by lazy` consruct.

Anyway, I think it is not related to the issue. From looking on cockroachdb I found this open issue that might be related:
https://github.com/cockroachdb/cockroach/issues/32501

**Comment by leenux** [comment]
Thank you for singleton code.
I am waiting cockroach to fix.

**Comment by oshai** [comment]
can we close this issue for now?
